services:
  - type: web
    name: blazor-server-net9
    env: docker
    plan: starter
    branch: main
    rootDirectory: TailwindMauiBlazorApp.Web
    buildCommand: "dotnet publish -c Release -o publish"
    startCommand: "dotnet publish/TailwindBlazorApp.Web.dll"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
        value: "5432"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
        sync: false